const iconData = [
    { code: 'cup', label: 'Copa de campeones' },
    { code: 'dis', label: 'Señor silla de ruedas' },
    { code: 'strs', label: '3 estrellas' },
    { code: 'bed', label: 'Cama azul' },
    { code: 'buk', label: 'Libro' },
    { code: 'bedf', label: 'Fuera de cama, cama inclinada' },
    { code: 'brgt', label: 'Brillo sol y luna adentro' },
    { code: 'sol', label: 'Sol' },
    { code: 'blnd', label: 'Ciego o señor con bastón' },
    { code: 'wif', label: 'Bluetooth o Wi-Fi' },
    { code: 'calnd', label: 'Calendario repetir' },
    { code: 'tatr', label: 'Teatro' },
    { code: 'liqr', label: 'Licor' },
    { code: 'dog', label: 'Perro' },
    { code: 'nodg', label: 'Prohibido perro' },
    { code: 'out', label: 'Aire libre, montaña' },
    { code: 'evnt', label: 'Se repite evento calendario' },
    { code: 'slct', label: 'Dedo seleccionando ícono' },
    { code: 'phto', label: 'Cámara fotográfica' },
    { code: 'clean', label: 'Lavarse las manos' },
    { code: 'car', label: 'Auto o carro' },
    { code: 'bbcr', label: 'Stroller o carrito de bebé' },
    { code: 'hous', label: 'Casa con chimenea' },
    { code: 'nocrd', label: 'No usar tarjeta para pago' },
    { code: 'card', label: 'Pago con tarjeta' },
    { code: 'bike', label: 'Bicicleta' },
    { code: 'run', label: 'Persona corriendo' },
    { code: 'tren', label: 'Tren' },
    { code: 'wc', label: 'Hombre y mujer símbolo de baños' },
    { code: 'wc2', label: 'Baño orinal' },
    { code: 'eat', label: 'Cubiertos' },
    { code: 'noeat', label: 'Cubiertos tachados prohibido' },
    { code: 'nomny', label: 'No dinero signo pesos tachado' },
    { code: 'old', label: 'Viej@ ancian@' },
    { code: 'pwer', label: 'Enchufe energía conexión' },
    { code: 'fmly', label: 'Familia' },
    { code: 'alli', label: 'Señal dirigirse flecha' },
    { code: 'trip', label: 'Aventón o señor con equipaje' },
    { code: 'mny', label: 'Signo pesos' },
    { code: '18ms', label: 'Mayor de 18' },
    { code: 'bby', label: 'Carita de bebé' },
    { code: 'fum', label: 'Cigarrillo' },
    { code: 'nofum', label: 'Cigarrillo tachado' }
];

export default iconData;